### ISSUE TITLE
list fixtures without executing them

### ISSUE THREAD

**Issue by brutus** [darrenburns/ward#315] opened 2022-02-18 19:15 UTC
It seems to me that running `ward fixtures` executes the fixtures found before listing them. If so,  a side-effect-free listing would be nice.

**Comment by JoshKarpel** [comment] 2022-02-20 02:21
Hi @brutus , do you have a reproducible example of this? I'm not able to reproduce it inside Ward's own test suite. `ward fixtures` need to import the modules, so any decorators you have on your fixtures will be evaluated (just like any other module-level code), but the bodies of the fixture functions shouldn't be executed.

**Comment by darrenburns** [comment] 2022-03-19 17:20
I'm going to close this, I suspect you were maybe doing something like `def _(f=my_fixture())` instead of `def _(f=my_fixture)`. If I'm wrong and you can provide a reproducible example feel free to create another issue 🙂

**Closed by darrenburns** 2022-03-19 17:20 UTC

**Comment by brutus** [comment] 2022-03-21 10:19
Apologies for not getting back earlier, I completely forgot about this :see_no_evil: Thank you both for your responses. While I currently have no access to the code in question, a quick test works fine though. 

I suspect the issue might have been caused by the decorators I put on the request session created in one of the fixtures. Anyway, if I'll find something concrete later, I'll come back with more info and reopen this.

```python
# test_host.py
"""
When running `ward fixtures` with the environment variable not set, 
it bailed on me b/c of the `KeyError`; works fine like this m)
"""
import os

from ward import fixture
from ward import test


@fixture(scope="global")
def host():
    return os.environ["TEST_HOST"]


@fixture(scope="global")
def client(host=host):
    yield f"return client based on '{host}'"
    # cleanup...


@test("check host")
def _(host=host):
    assert host


@test("check client")
def _(client=client):
    assert client
```
