### ISSUE TITLE
ward and singletons

### ISSUE THREAD

**Issue by dodgyville** [darrenburns/ward#138] opened 2020-03-01 07:49 UTC
Hi, I have a third party module that imports a singleton. I'm finding that between tests the singleton keeps its memory of previous tests. 

Here's a cribbed example:
```
from pyswip import Prolog
from ward import test


@test("test1")
def test1():
    prolog = Prolog()
    prolog.assertz('is_a(a, b)')
    result = list(prolog.query("is_a(a,b)"))
    assert result == [{}]


@test("test2")
def test2():
    prolog = Prolog()
    prolog.assertz('is_a(a, b)')
    result = list(prolog.query("is_a(a,b)"))
    assert result == [{}]

```

 PASS  test_ward test1
 FAIL  test_ward: test2

**Comment by darrenburns** [comment] 2020-03-03 07:42
Hi, I don't know anything about the pyswip library you're using but it seems unlikely that this is an issue with Ward. Ward uses fixtures to isolate state between tests, and the extent of that isolation is determined by the `scope` parameter of the `@fixture` decorator.

It has no other means of "forgetting" things between tests, and that's by design.

From looking at the examples of `pyswip` the only thing I can suggest is trying this, and if it doesn't work I'm out of ideas:

```python
from ward import fixture, test

# This fixture will be instantiated when first needed and
# kept around for the full run
@fixture(scope="global")
def prolog():
    return Prolog()

@test("test1")
def _(p=prolog):
    p.assertz('is_a(a, b)')
    result = list(p.query("is_a(a,b)"))
    assert result == [{}]

@test("test2")
def _(p=prolog):
    p.assertz('is_a(a, b)')
    result = list(p.query("is_a(a,b)"))
    assert result == [{}]
```

**Comment by darrenburns** [comment] 2020-03-11 16:42
Closing this for now to clean up the issues a bit. Don't hesitate to re-open if you'd like to continue the discussion though 😄

**Closed by darrenburns** 2020-03-11 16:42 UTC
